# SwiftLint configuration: Only fail CI on the most severe rules

opt_in_rules:
  - force_cast
  - cyclomatic_complexity
  # - line_length (disabled for now)
  # - function_parameter_count (disabled for now)

# Configure cyclomatic_complexity (default error is 10, can adjust if needed)
cyclomatic_complexity:
  warning: 10
  error: 10

# Disable all other rules, including line_length and function_parameter_count
# (List only rules you want to disable, or use 'disabled_rules: all' and re-enable above if you want to be strict)
disabled_rules:
  - identifier_name
  - function_body_length
  - type_body_length
  - file_length
  - todo
  - trailing_newline
  - vertical_whitespace
  - orphaned_doc_comment
  - nesting
  - comment_spacing
  - statement_position
  - empty_parentheses_with_trailing_closure
  - switch_case_alignment
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - colon
  - comma
  - comma_inheritance
  - opening_brace
  - closing_brace
  - trailing_comma
  - trailing_semicolon
  - trailing_whitespace
  - leading_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - multiple_closures_with_trailing_closure
  - unused_closure_parameter
  - unused_optional_binding
  - unused_parameter
  - unused_setter_value
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_declaration
  - redundant_optional_initialization
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_self_in_closure
  - redundant_sendable
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - empty_enum_arguments
  - empty_count
  - empty_collection_literal
  - empty_parameters
  - empty_string
  - empty_xctest_method
  - for_where
  - prefer_for_where
  - line_length
  - function_parameter_count

# Remove any invalid or misspelled rule identifiers